### ISSUE TITLE
Extensions are not loaded / enabled on first provision

### ISSUE THREAD

**Issue by RobQuistNL** [Enrise/zendserver-formula#7]
Provisioning with these settings causes SSH2 to not be enabled;

```
zendserver:
  admin_password: XXXXX
  version:
    zend: '2018.0'
    php: '7.2'
  webserver: nginx
  enable_itk: False
  bootstrap: True
  license:
    order: XXXXX
    serial: XXXXXX
  directives:
    date.timezone: 'Europe/Amsterdam'
    zray.enable: 0
    zray.enable_cli: 0
    zray.collect_backtrace: 0
    zray.collect_backtrace.errors_warnings: 0
    zray.collect_backtrace.sql_queries: 0
    zray.enable_extensibility: 0
    zend_statistics_extension.enable_apps_plugins: 0
    zend_statistics.enable: 0
    zend_url_insight.enable: 0
    zend_codetracing.enable: 0

  disable_extensions:
    - '"Zend Statistics"'
#   - '"Zend Monitor"' #this one is even broken in the web interface of ZS
  enable_extensions:
    - ssh2

```

![image](https://user-images.githubusercontent.com/1442796/47661205-e0555200-db98-11e8-841f-32a984f53053.png)
